/**
 * Drizzle schema -- every table from the data model in CLAUDE.md.
 *
 * The whole schema is defined now, in chunk 1, even though most of these tables
 * are not written to until later chunks. That is deliberate: getting the shape
 * right once is easier than migrating a live database five times. Tables that
 * later chunks own are marked with the chunk that starts using them.
 *
 * Two conventions used throughout:
 *  - Primary keys are UUIDs generated by Postgres, so nothing has to coordinate
 *    IDs across requests.
 *  - Deleting a parent row deletes its children (`onDelete: "cascade"`). Delete a
 *    prototype and its versions, sessions, messages and feedback go with it.
 */

import { relations, sql } from "drizzle-orm";
import {
  boolean,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

/* --------------------------------------------------------------------------
 * Enums
 *
 * These become real Postgres enum types, so the database itself rejects a bad
 * value rather than trusting the application to have got it right.
 * ------------------------------------------------------------------------ */

/** A new version is either an iteration on the last one, or a parallel option. */
export const versionTypeEnum = pgEnum("version_type", ["revision", "option"]);

/**
 * How hard the assistant pushes in a review. Set per prototype.
 *
 * These are not three different products -- "review" is the ordinary case and
 * the other two are its edges. Browse answers questions and never interjects;
 * verify works through the acceptance criteria and asks for a decision at the
 * end. prompts/assistant.md is where the behaviour of each is written down.
 *
 * The reviewer's own intent still overrides this. Someone who opens a verify
 * prototype just to look around gets browse behaviour, because running a
 * checklist at them is how you lose the one person who bothered to come.
 */
export const assistantModeEnum = pgEnum("assistant_mode", [
  "browse",
  "review",
  "verify",
]);

/** How the reviewer pointed at something. Chunks 6 and 7. */
export const annotationKindEnum = pgEnum("annotation_kind", ["select", "point", "draw"]);

/** Who said it. Chunk 4. */
export const messageRoleEnum = pgEnum("message_role", ["user", "assistant"]);

/**
 * What the reviewer is here as. Picked by them, after their name.
 *
 * This changes what the assistant asks about, never how hard it pushes -- that
 * is the prototype's mode. A developer gets asked about the states that are not
 * shown; a product owner gets asked whether it solves the problem. Same
 * assistant, different questions.
 *
 * "other" is not a fallback for a missing answer. It is a real choice, and it
 * means plain language and no ticket numbers.
 */
export const reviewerRoleEnum = pgEnum("reviewer_role", [
  "product_owner",
  "developer",
  "qa",
  "designer",
  "other",
]);

/** How bad is it. Chunk 5. */
export const severityEnum = pgEnum("severity", [
  "blocker",
  "major",
  "minor",
  "preference",
  "new_request",
]);

/** What I decided to do about it. Null until triaged. Chunk 5. */
export const dispositionEnum = pgEnum("disposition", [
  "done",
  "wont_do",
  "deferred",
  "needs_discussion",
]);

/** Verdict on one acceptance criterion. Chunk 9. */
export const acResultEnum = pgEnum("ac_result_value", [
  "met",
  "not_met",
  "needs_discussion",
  "not_verifiable",
]);

/* --------------------------------------------------------------------------
 * prototype
 *
 * One row per thing being reviewed. The reviewer link /r/[id] points here and
 * never changes, even as versions come and go.
 * ------------------------------------------------------------------------ */

export const prototype = pgTable("prototype", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  ticket: text("ticket"),
  description: text("description"),
  /** Hashed reviewer password. Never store the plain text. Written in chunk 2. */
  passwordHash: text("password_hash").notNull(),
  /** Names offered in the reviewer name picker. Postgres text[]. */
  reviewerNames: text("reviewer_names").array().notNull().default([]),
  /**
   * How the assistant behaves in this prototype's reviews. Defaults to
   * "review", which is the ordinary case, so an existing prototype that has
   * never been told behaves the way it always did.
   */
  mode: assistantModeEnum("mode").notNull().default("review"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/* --------------------------------------------------------------------------
 * version
 *
 * One uploaded HTML file plus the knowledge base that describes it. Exactly one
 * version per prototype has is_current true, and the unique index below is what
 * guarantees that rather than leaving it to application code.
 * ------------------------------------------------------------------------ */

export const version = pgTable(
  "version",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    prototypeId: uuid("prototype_id")
      .notNull()
      .references(() => prototype.id, { onDelete: "cascade" }),
    /** Human label such as "v1". */
    label: text("label").notNull(),
    /** One line on what changed since the last version. Shown to reviewers. */
    changedNote: text("changed_note"),
    /**
     * Where the HTML lives in Vercel Blob. Never used as an iframe src -- see
     * the same-origin constraint in CLAUDE.md. The /p/[versionId] route fetches
     * from here and re-serves the HTML from our own origin.
     */
    htmlBlobUrl: text("html_blob_url").notNull(),
    /** The markdown that becomes the assistant's context. Chunk 4. */
    knowledgeBaseText: text("knowledge_base_text"),
    /**
     * The situation to put the reviewer in before they start: who they are
     * pretending to be and what has just happened. Read out in the assistant's
     * opening, and only when there is one -- most prototypes do not need it.
     */
    scenario: text("scenario"),
    type: versionTypeEnum("type").notNull().default("revision"),
    isCurrent: boolean("is_current").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("version_prototype_id_idx").on(table.prototypeId),
    /**
     * Partial unique index: at most one current version per prototype. Postgres
     * only indexes rows where is_current is true, so any number of old versions
     * can sit at false.
     */
    uniqueIndex("version_one_current_per_prototype_idx")
      .on(table.prototypeId)
      .where(sql`${table.isCurrent}`),
  ],
);

/* --------------------------------------------------------------------------
 * task -- what a reviewer is asked to try. Chunk 9.
 * ------------------------------------------------------------------------ */

export const task = pgTable(
  "task",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    versionId: uuid("version_id")
      .notNull()
      .references(() => version.id, { onDelete: "cascade" }),
    /** Manual ordering, so tasks can be dragged into sequence. */
    sortOrder: integer("sort_order").notNull().default(0),
    goal: text("goal").notNull(),
    successState: text("success_state"),
  },
  (table) => [index("task_version_id_idx").on(table.versionId)],
);

/* --------------------------------------------------------------------------
 * criterion -- one acceptance criterion. Chunk 9.
 * ------------------------------------------------------------------------ */

export const criterion = pgTable(
  "criterion",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    versionId: uuid("version_id")
      .notNull()
      .references(() => version.id, { onDelete: "cascade" }),
    /** Manual ordering, so criteria keep the order they were written in. */
    sortOrder: integer("sort_order").notNull().default(0),
    /** The reference from the ticket, e.g. "AC3". */
    ref: text("ref"),
    text: text("text").notNull(),
    /** Where in the source document this came from. */
    whereFound: text("where_found"),
    /** False when it simply cannot be checked in a clickable prototype. */
    verifiableInPrototype: boolean("verifiable_in_prototype").notNull().default(true),
  },
  (table) => [index("criterion_version_id_idx").on(table.versionId)],
);

/* --------------------------------------------------------------------------
 * not_built -- things deliberately absent from this prototype, so the
 * assistant can say "that is out of scope" instead of guessing. Chunk 4.
 * ------------------------------------------------------------------------ */

export const notBuilt = pgTable(
  "not_built",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    versionId: uuid("version_id")
      .notNull()
      .references(() => version.id, { onDelete: "cascade" }),
    /** Manual ordering, so the list keeps the order it was written in. */
    sortOrder: integer("sort_order").notNull().default(0),
    text: text("text").notNull(),
  },
  (table) => [index("not_built_version_id_idx").on(table.versionId)],
);

/* --------------------------------------------------------------------------
 * session -- one reviewer's visit. Created after they pass the password screen
 * and pick a name. Chunk 3.
 * ------------------------------------------------------------------------ */

export const session = pgTable(
  "session",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    versionId: uuid("version_id")
      .notNull()
      .references(() => version.id, { onDelete: "cascade" }),
    reviewerName: text("reviewer_name").notNull(),
    /**
     * Defaults to "other", which is the safe answer: plain language and no
     * jargon. Sessions that started before roles existed read as "other" too,
     * which is exactly right -- nobody asked them.
     */
    reviewerRole: reviewerRoleEnum("reviewer_role").notNull().default("other"),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(),
    /** Set when they press "finish review". Null means still in progress. */
    completedAt: timestamp("completed_at", { withTimezone: true }),
  },
  (table) => [index("session_version_id_idx").on(table.versionId)],
);

/* --------------------------------------------------------------------------
 * message -- the assistant conversation transcript. Chunk 4.
 * ------------------------------------------------------------------------ */

export const message = pgTable(
  "message",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    sessionId: uuid("session_id")
      .notNull()
      .references(() => session.id, { onDelete: "cascade" }),
    role: messageRoleEnum("role").notNull(),
    content: text("content").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("message_session_id_idx").on(table.sessionId)],
);

/* --------------------------------------------------------------------------
 * annotation -- where in the prototype the reviewer was pointing. Chunks 6-7.
 * ------------------------------------------------------------------------ */

export const annotation = pgTable(
  "annotation",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    sessionId: uuid("session_id")
      .notNull()
      .references(() => session.id, { onDelete: "cascade" }),
    kind: annotationKindEnum("kind").notNull(),
    /** The data-screen value that was visible at the time. */
    screenId: text("screen_id"),
    /** Set for kind 'select'. */
    cssSelector: text("css_selector"),
    /** Pin or path coordinates for kind 'point' and 'draw'. */
    coordsJson: jsonb("coords_json"),
    /** Screenshot of the annotated area, in Vercel Blob. */
    screenshotBlobUrl: text("screenshot_blob_url"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("annotation_session_id_idx").on(table.sessionId)],
);

/* --------------------------------------------------------------------------
 * feedback -- the point of the whole application. Chunk 5.
 *
 * annotation_id, task_id and criterion_id are all optional: a reviewer can make
 * a point without pointing at anything, and without it belonging to a task.
 * Those three use "set null" rather than "cascade" so deleting an annotation
 * never silently deletes the feedback attached to it.
 * ------------------------------------------------------------------------ */

export const feedback = pgTable(
  "feedback",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    sessionId: uuid("session_id")
      .notNull()
      .references(() => session.id, { onDelete: "cascade" }),
    annotationId: uuid("annotation_id").references(() => annotation.id, {
      onDelete: "set null",
    }),
    screenId: text("screen_id"),
    taskId: uuid("task_id").references(() => task.id, { onDelete: "set null" }),
    criterionId: uuid("criterion_id").references(() => criterion.id, {
      onDelete: "set null",
    }),
    /** What the reviewer expected to happen. */
    expected: text("expected"),
    /** What actually happened. */
    happened: text("happened"),
    note: text("note"),
    severity: severityEnum("severity").notNull().default("minor"),
    /** Null until I triage it in the admin area. */
    disposition: dispositionEnum("disposition"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("feedback_session_id_idx").on(table.sessionId),
    index("feedback_annotation_id_idx").on(table.annotationId),
    index("feedback_severity_idx").on(table.severity),
  ],
);

/* --------------------------------------------------------------------------
 * ac_result -- one reviewer's verdict on one criterion. Chunk 9.
 *
 * The unique index keeps a reviewer from having two verdicts on the same
 * criterion in one session: changing their mind updates the row.
 * ------------------------------------------------------------------------ */

export const acResult = pgTable(
  "ac_result",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    sessionId: uuid("session_id")
      .notNull()
      .references(() => session.id, { onDelete: "cascade" }),
    criterionId: uuid("criterion_id")
      .notNull()
      .references(() => criterion.id, { onDelete: "cascade" }),
    result: acResultEnum("result").notNull(),
    note: text("note"),
  },
  (table) => [
    uniqueIndex("ac_result_session_criterion_idx").on(table.sessionId, table.criterionId),
  ],
);

/* --------------------------------------------------------------------------
 * Relations
 *
 * These are Drizzle-level only -- they add no SQL. They let queries read as
 * `with: { versions: true }` instead of hand-written joins.
 * ------------------------------------------------------------------------ */

export const prototypeRelations = relations(prototype, ({ many }) => ({
  versions: many(version),
}));

export const versionRelations = relations(version, ({ one, many }) => ({
  prototype: one(prototype, {
    fields: [version.prototypeId],
    references: [prototype.id],
  }),
  tasks: many(task),
  criteria: many(criterion),
  notBuilt: many(notBuilt),
  sessions: many(session),
}));

export const taskRelations = relations(task, ({ one }) => ({
  version: one(version, { fields: [task.versionId], references: [version.id] }),
}));

export const criterionRelations = relations(criterion, ({ one, many }) => ({
  version: one(version, { fields: [criterion.versionId], references: [version.id] }),
  acResults: many(acResult),
}));

export const notBuiltRelations = relations(notBuilt, ({ one }) => ({
  version: one(version, { fields: [notBuilt.versionId], references: [version.id] }),
}));

export const sessionRelations = relations(session, ({ one, many }) => ({
  version: one(version, { fields: [session.versionId], references: [version.id] }),
  messages: many(message),
  annotations: many(annotation),
  feedback: many(feedback),
  acResults: many(acResult),
}));

export const messageRelations = relations(message, ({ one }) => ({
  session: one(session, { fields: [message.sessionId], references: [session.id] }),
}));

export const annotationRelations = relations(annotation, ({ one, many }) => ({
  session: one(session, { fields: [annotation.sessionId], references: [session.id] }),
  feedback: many(feedback),
}));

export const feedbackRelations = relations(feedback, ({ one }) => ({
  session: one(session, { fields: [feedback.sessionId], references: [session.id] }),
  annotation: one(annotation, {
    fields: [feedback.annotationId],
    references: [annotation.id],
  }),
  task: one(task, { fields: [feedback.taskId], references: [task.id] }),
  criterion: one(criterion, {
    fields: [feedback.criterionId],
    references: [criterion.id],
  }),
}));

export const acResultRelations = relations(acResult, ({ one }) => ({
  session: one(session, { fields: [acResult.sessionId], references: [session.id] }),
  criterion: one(criterion, {
    fields: [acResult.criterionId],
    references: [criterion.id],
  }),
}));

/* --------------------------------------------------------------------------
 * Inferred types, so the rest of the app never redeclares these shapes.
 * ------------------------------------------------------------------------ */

export type Prototype = typeof prototype.$inferSelect;
export type NewPrototype = typeof prototype.$inferInsert;
export type Version = typeof version.$inferSelect;
export type NewVersion = typeof version.$inferInsert;
export type Task = typeof task.$inferSelect;
export type Criterion = typeof criterion.$inferSelect;
export type NotBuilt = typeof notBuilt.$inferSelect;
export type Session = typeof session.$inferSelect;
export type Message = typeof message.$inferSelect;
export type Annotation = typeof annotation.$inferSelect;
export type Feedback = typeof feedback.$inferSelect;
export type AcResult = typeof acResult.$inferSelect;
export type ReviewerRole = (typeof reviewerRoleEnum.enumValues)[number];
export type Severity = (typeof severityEnum.enumValues)[number];
export type Disposition = (typeof dispositionEnum.enumValues)[number];
